import type {
  BoqCategory,
  BoqLineItem,
  ExecutionStage,
  SiteSubStage,
  SupplierQuote,
} from "@/types/execution";

function q(
  supplierId: number,
  supplierName: string,
  price: number,
): SupplierQuote {
  return { supplierId, supplierName, price };
}

function item(
  partial: Omit<BoqLineItem, "negotiationStatus" | "paymentStatus" | "contractUploaded"> &
    Partial<Pick<BoqLineItem, "negotiationStatus" | "paymentStatus" | "contractUploaded">>,
): BoqLineItem {
  return {
    negotiationStatus: "pending",
    paymentStatus: "not-paid",
    contractUploaded: false,
    ...partial,
  };
}

export const EXECUTION_STAGES: ExecutionStage[] = [
  {
    id: 1,
    name: "BOQ Development",
    detail: "Bill of Quantities built from confirmed detail drawings. Connected to the supplier module. Up to 3 quotations per line item.",
    status: "complete",
    icon: "receipt_long",
  },
  {
    id: 2,
    name: "Supplier Negotiation",
    detail: "Negotiation status tracked per supplier — pending, in progress, or agreed.",
    status: "in-progress",
    icon: "handshake",
  },
  {
    id: 3,
    name: "Supplier Confirmation",
    detail: "Supplier confirmed and locked in for each BOQ line item.",
    status: "upcoming",
    icon: "verified",
  },
  {
    id: 4,
    name: "Advance Payment",
    detail: "Payment status logged — not paid, partially paid, or paid.",
    status: "upcoming",
    icon: "payments",
  },
  {
    id: 5,
    name: "Contract Sign",
    detail: "Supplier contract signed — upload confirmation document.",
    status: "upcoming",
    icon: "gavel",
  },
  {
    id: 6,
    name: "Commence Project",
    detail: "Site work begins. Full sub-stage breakdown with parallel timelines.",
    status: "upcoming",
    icon: "construction",
  },
];

export const BOQ_CATEGORIES: BoqCategory[] = [
  {
    id: "A",
    label: "Preliminaries",
    icon: "engineering",
    color: "#1B2A4A",
    accentBg: "#E2E8F0",
    budget: 450_000,
    durationDays: 5,
    items: [
      item({
        id: 1,
        item: "Removal Work",
        description: "Strip-out of existing finishes, fixtures, and debris haul-away",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "LS",
        qty: 1,
        rate: 185_000,
        quotes: [
          q(8, "Roccia Naturale", 172_000),
          q(5, "Gres Ceramiche", 198_000),
        ],
        selectedSupplierId: 8,
        designFirmPrice: 220_000,
        negotiationStatus: "agreed",
        paymentStatus: "partial",
      }),
      item({
        id: 2,
        item: "Site Preparation Work",
        description: "Protection, access, temporary power, and site setup",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "LS",
        qty: 1,
        rate: 95_000,
        quotes: [q(8, "Roccia Naturale", 88_000), q(10, "Lanka Site Works", 102_000)],
        selectedSupplierId: 8,
        designFirmPrice: 115_000,
        negotiationStatus: "agreed",
      }),
      item({
        id: 3,
        item: "Site Deep Clean",
        description: "Mandatory deep clean after high-dust works",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "LS",
        qty: 2,
        rate: 45_000,
        quotes: [q(11, "Sparkle Facilities", 42_000)],
        selectedSupplierId: 11,
        designFirmPrice: 55_000,
        negotiationStatus: "in-progress",
      }),
    ],
  },
  {
    id: "B",
    label: "Masonry and Cement Work",
    icon: "foundation",
    color: "#92400E",
    accentBg: "#FEF3C7",
    budget: 1_250_000,
    durationDays: 12,
    items: [
      item({
        id: 4,
        item: "Walls",
        description: "Blockwork, plaster, and cement rendering",
        lengthIn: "240",
        widthIn: "8",
        heightIn: "108",
        unit: "m²",
        qty: 86,
        rate: 8_500,
        quotes: [
          q(8, "Roccia Naturale", 8_200),
          q(12, "Colombo Masonry Co.", 8_750),
          q(13, "Dehiwala Builders", 7_950),
        ],
        selectedSupplierId: 13,
        designFirmPrice: 9_800,
        negotiationStatus: "agreed",
        paymentStatus: "partial",
      }),
      item({
        id: 5,
        item: "Floor",
        description: "Screed and cement floor preparation",
        lengthIn: "480",
        widthIn: "360",
        heightIn: "",
        unit: "m²",
        qty: 112,
        rate: 3_200,
        quotes: [q(8, "Roccia Naturale", 3_050), q(12, "Colombo Masonry Co.", 3_400)],
        selectedSupplierId: null,
        designFirmPrice: 3_800,
        negotiationStatus: "in-progress",
      }),
    ],
  },
  {
    id: "C",
    label: "Electrical and Wiring Work",
    icon: "bolt",
    color: "#D97706",
    accentBg: "#FEF3C7",
    budget: 2_850_000,
    durationDays: 14,
    items: [
      item({
        id: 6,
        item: "Electrical Wiring work",
        description: "Concealed or open wiring and installation of conduits",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "LS",
        qty: 1,
        rate: 980_000,
        quotes: [
          q(14, "Volt Lanka Electrical", 920_000),
          q(15, "Ceylon Circuits", 1_050_000),
        ],
        selectedSupplierId: 14,
        designFirmPrice: 1_180_000,
        negotiationStatus: "agreed",
      }),
      item({
        id: 7,
        item: "DB Modifications",
        description: "Installation of distribution box etc.",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "nos",
        qty: 2,
        rate: 85_000,
        quotes: [q(14, "Volt Lanka Electrical", 78_000), q(15, "Ceylon Circuits", 91_000)],
        selectedSupplierId: 14,
        designFirmPrice: 105_000,
        negotiationStatus: "agreed",
      }),
      item({
        id: 8,
        item: "Socket outlets",
        description: "Power outlets as per electrical plan",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "nos",
        qty: 48,
        rate: 4_200,
        quotes: [q(14, "Volt Lanka Electrical", 3_900), q(15, "Ceylon Circuits", 4_500)],
        selectedSupplierId: 14,
        designFirmPrice: 5_200,
        negotiationStatus: "in-progress",
      }),
      item({
        id: 9,
        item: "Light points",
        description: "Any type of lighting",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "nos",
        qty: 62,
        rate: 6_800,
        quotes: [
          q(3, "Flos Architectural", 7_200),
          q(14, "Volt Lanka Electrical", 6_400),
          q(7, "Cattaneo Illuminazione", 7_800),
        ],
        selectedSupplierId: 14,
        designFirmPrice: 8_500,
        negotiationStatus: "agreed",
      }),
      item({
        id: 10,
        item: "AC Points",
        description: "Dedicated circuits for split units",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "nos",
        qty: 6,
        rate: 18_500,
        quotes: [q(14, "Volt Lanka Electrical", 17_000)],
        selectedSupplierId: null,
        designFirmPrice: 22_000,
      }),
      item({
        id: 11,
        item: "Other Wiring",
        description: "For electrical equipment, fans, etc.",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "LS",
        qty: 1,
        rate: 120_000,
        quotes: [q(14, "Volt Lanka Electrical", 110_000), q(15, "Ceylon Circuits", 128_000)],
        selectedSupplierId: 14,
        designFirmPrice: 145_000,
        negotiationStatus: "pending",
      }),
      item({
        id: 12,
        item: "Electrical Accessories",
        description: "Switches, dimmers, faceplates",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "LS",
        qty: 1,
        rate: 165_000,
        quotes: [q(14, "Volt Lanka Electrical", 148_000)],
        selectedSupplierId: 14,
        designFirmPrice: 195_000,
        negotiationStatus: "in-progress",
      }),
    ],
  },
  {
    id: "D",
    label: "Wall Work",
    icon: "wallpaper",
    color: "#0891B2",
    accentBg: "#E0F7FA",
    budget: 3_400_000,
    durationDays: 16,
    items: [
      item({
        id: 13,
        item: "Wall Finishing Work",
        description: "Wall surface prepping",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "m²",
        qty: 210,
        rate: 2_800,
        quotes: [q(12, "Colombo Masonry Co.", 2_650), q(16, "Atelier Finishes", 2_950)],
        selectedSupplierId: 12,
        designFirmPrice: 3_400,
        negotiationStatus: "agreed",
      }),
      item({
        id: 14,
        item: "Paint Work",
        description: "Premium interior emulsion, two coats",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "m²",
        qty: 210,
        rate: 1_450,
        quotes: [q(16, "Atelier Finishes", 1_380), q(17, "ColourCraft SL", 1_520)],
        selectedSupplierId: 16,
        designFirmPrice: 1_800,
        negotiationStatus: "agreed",
      }),
      item({
        id: 15,
        item: "Partitioning",
        description: "All types of partitioning",
        lengthIn: "144",
        widthIn: "4",
        heightIn: "108",
        unit: "m²",
        qty: 28,
        rate: 12_500,
        quotes: [q(6, "Bertolotto Porte", 13_200), q(18, "Grid Joinery", 11_800)],
        selectedSupplierId: null,
        designFirmPrice: 15_000,
      }),
      item({
        id: 16,
        item: "Wall Surface Work",
        description: "Includes panelling, wall paper, or wall stickers",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "m²",
        qty: 42,
        rate: 18_000,
        quotes: [q(4, "Rubelli Textiles", 19_500), q(16, "Atelier Finishes", 16_800)],
        selectedSupplierId: 16,
        designFirmPrice: 22_000,
        negotiationStatus: "in-progress",
      }),
    ],
  },
  {
    id: "E",
    label: "Doors and Windows",
    icon: "door_front",
    color: "#7C3AED",
    accentBg: "#EDE9FE",
    budget: 2_200_000,
    durationDays: 10,
    items: [
      item({
        id: 17,
        item: "Door frames",
        description: "Timber and aluminium frames as specified",
        lengthIn: "36",
        widthIn: "6",
        heightIn: "84",
        image: "/placeholder-boq.svg",
        unit: "nos",
        qty: 8,
        rate: 28_000,
        quotes: [q(6, "Bertolotto Porte", 26_500), q(18, "Grid Joinery", 29_800)],
        selectedSupplierId: 6,
        designFirmPrice: 34_000,
        negotiationStatus: "agreed",
      }),
      item({
        id: 18,
        item: "Door installations",
        description: "Includes locks, handles and hinges",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "nos",
        qty: 8,
        rate: 18_500,
        quotes: [q(6, "Bertolotto Porte", 17_200), q(18, "Grid Joinery", 19_400)],
        selectedSupplierId: 6,
        designFirmPrice: 22_500,
        negotiationStatus: "agreed",
      }),
      item({
        id: 19,
        item: "Window frames",
        description: "Powder-coated aluminium frames",
        lengthIn: "60",
        widthIn: "4",
        heightIn: "48",
        image: "/placeholder-boq.svg",
        unit: "nos",
        qty: 12,
        rate: 42_000,
        quotes: [q(19, "Island Aluminium", 39_500), q(6, "Bertolotto Porte", 44_000)],
        selectedSupplierId: 19,
        designFirmPrice: 52_000,
        negotiationStatus: "in-progress",
      }),
      item({
        id: 20,
        item: "Window installations",
        description: "Includes locks, handles and hinges",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "nos",
        qty: 12,
        rate: 12_000,
        quotes: [q(19, "Island Aluminium", 11_200)],
        selectedSupplierId: 19,
        designFirmPrice: 15_000,
      }),
    ],
  },
  {
    id: "F",
    label: "Ceiling Work",
    icon: "roofing",
    color: "#0E7C86",
    accentBg: "rgba(14,124,134,0.10)",
    budget: 3_100_000,
    durationDays: 12,
    items: [
      item({
        id: 21,
        item: "Ceiling base",
        description: "Framework or soffit",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "m²",
        qty: 112,
        rate: 4_800,
        quotes: [q(20, "Skyline Ceilings", 4_500), q(12, "Colombo Masonry Co.", 5_100)],
        selectedSupplierId: 20,
        designFirmPrice: 5_800,
        negotiationStatus: "agreed",
      }),
      item({
        id: 22,
        item: "Ceiling",
        description: "Panels, gypsum boards or slab finish",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "m²",
        qty: 112,
        rate: 9_200,
        quotes: [q(20, "Skyline Ceilings", 8_700), q(16, "Atelier Finishes", 9_600)],
        selectedSupplierId: 20,
        designFirmPrice: 11_000,
        negotiationStatus: "agreed",
      }),
    ],
  },
  {
    id: "G",
    label: "Flooring Work",
    icon: "layers",
    color: "#8B5CF6",
    accentBg: "#EDE9FE",
    budget: 4_200_000,
    durationDays: 10,
    items: [
      item({
        id: 23,
        item: "Floor prepping work",
        description: "Preparation of floor for the finalized flooring solution",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "m²",
        qty: 112,
        rate: 2_100,
        quotes: [q(2, "Fiemme 3000", 2_400), q(5, "Gres Ceramiche", 1_950)],
        selectedSupplierId: 5,
        designFirmPrice: 2_600,
        negotiationStatus: "agreed",
      }),
      item({
        id: 24,
        item: "Flooring",
        description: "All types of flooring solutions",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        image: "/placeholder-boq.svg",
        unit: "m²",
        qty: 112,
        rate: 18_500,
        quotes: [
          q(2, "Fiemme 3000", 22_000),
          q(5, "Gres Ceramiche", 16_800),
          q(21, "Lanka Timber Floors", 17_400),
        ],
        selectedSupplierId: 5,
        designFirmPrice: 24_000,
        negotiationStatus: "agreed",
        paymentStatus: "partial",
      }),
    ],
  },
  {
    id: "H",
    label: "Furniture",
    icon: "chair",
    color: "#BE185D",
    accentBg: "#FCE7F3",
    budget: 8_400_000,
    durationDays: 21,
    items: [
      item({
        id: 25,
        item: "Lobby seating",
        description: "Residential and commercial furniture — seating",
        lengthIn: "84",
        widthIn: "36",
        heightIn: "32",
        image: "/placeholder-boq.svg",
        unit: "nos",
        qty: 4,
        rate: 285_000,
        quotes: [
          q(1, "Poliform Milano", 310_000),
          q(22, "Colombo Craft Atelier", 265_000),
        ],
        selectedSupplierId: 22,
        designFirmPrice: 360_000,
        negotiationStatus: "agreed",
      }),
      item({
        id: 26,
        item: "Directors room storage",
        description: "Custom joinery storage wall",
        lengthIn: "144",
        widthIn: "24",
        heightIn: "96",
        image: "/placeholder-boq.svg",
        unit: "LS",
        qty: 1,
        rate: 1_850_000,
        quotes: [q(1, "Poliform Milano", 2_100_000), q(18, "Grid Joinery", 1_720_000)],
        selectedSupplierId: 18,
        designFirmPrice: 2_250_000,
        negotiationStatus: "in-progress",
      }),
    ],
  },
  {
    id: "I",
    label: "Decoration and Other Work",
    icon: "palette",
    color: "#EC4899",
    accentBg: "#FCE7F3",
    budget: 1_800_000,
    durationDays: 8,
    items: [
      item({
        id: 27,
        item: "Exterior modifications",
        description: "Entrance canopy and façade touch-up",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "LS",
        qty: 1,
        rate: 320_000,
        quotes: [q(8, "Roccia Naturale", 295_000)],
        selectedSupplierId: 8,
        designFirmPrice: 390_000,
        negotiationStatus: "pending",
      }),
      item({
        id: 28,
        item: "Plumbing Work",
        description: "Pantry and WC connections",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "LS",
        qty: 1,
        rate: 185_000,
        quotes: [q(23, "AquaFlow Plumbing", 168_000), q(24, "Island Pipeworks", 192_000)],
        selectedSupplierId: 23,
        designFirmPrice: 225_000,
        negotiationStatus: "agreed",
      }),
      item({
        id: 29,
        item: "Interior Decor",
        description: "Lump sum — art, plants, styling",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "LS",
        qty: 1,
        rate: 450_000,
        quotes: [q(22, "Colombo Craft Atelier", 420_000)],
        selectedSupplierId: 22,
        designFirmPrice: 580_000,
        negotiationStatus: "in-progress",
      }),
      item({
        id: 30,
        item: "Other",
        description: "Miscellaneous finishing items",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "LS",
        qty: 1,
        rate: 75_000,
        quotes: [],
        selectedSupplierId: null,
        designFirmPrice: 95_000,
      }),
    ],
  },
  {
    id: "J",
    label: "Additional Work",
    icon: "add_box",
    color: "#64748B",
    accentBg: "#F1F5F9",
    budget: 400_000,
    durationDays: 5,
    items: [
      item({
        id: 31,
        item: "Additional Work",
        description: "Any other additional work client requests after commencement",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "LS",
        qty: 1,
        rate: 0,
        quotes: [],
        selectedSupplierId: null,
        designFirmPrice: 0,
      }),
    ],
  },
  {
    id: "K",
    label: "Project Management and Supervision",
    icon: "supervisor_account",
    color: "#1B2A4A",
    accentBg: "#E2E8F0",
    budget: 1_200_000,
    durationDays: 45,
    items: [
      item({
        id: 32,
        item: "Project Management and Supervision",
        description: "GRID Interior site supervision and coordination — carried to summary",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "LS",
        qty: 1,
        rate: 1_200_000,
        quotes: [],
        selectedSupplierId: null,
        designFirmPrice: 1_200_000,
        negotiationStatus: "agreed",
        paymentStatus: "partial",
      }),
    ],
  },
  {
    id: "L",
    label: "Lump Sum Breakdown",
    icon: "shopping_bag",
    color: "#0E7C86",
    accentBg: "#CCFBF1",
    budget: 450_000,
    durationDays: 7,
    items: [
      item({
        id: 33,
        item: "Décor purchases",
        description: "Total list of purchases made using the lump sum assigned for décor",
        lengthIn: "",
        widthIn: "",
        heightIn: "",
        unit: "LS",
        qty: 1,
        rate: 450_000,
        quotes: [q(22, "Colombo Craft Atelier", 430_000)],
        selectedSupplierId: 22,
        designFirmPrice: 450_000,
        negotiationStatus: "in-progress",
      }),
    ],
  },
];

export const SITE_SUBSTAGES: SiteSubStage[] = [
  {
    id: "6.1",
    number: "6.1",
    name: "Mobilisation",
    detail: "Days 1–3. Site preparation: purchases, cover floors with polythene, get equipment ready.",
    status: "complete",
    startDay: 1,
    durationDays: 3,
    checkpoint: false,
  },
  {
    id: "6.2",
    number: "6.2",
    name: "Preliminary Works",
    detail: "Begin preliminary works. Colour selection and furniture detailing finalized with suppliers.",
    status: "complete",
    startDay: 3,
    durationDays: 5,
    checkpoint: false,
  },
  {
    id: "6.3",
    number: "6.3",
    name: "Floor Mapping",
    detail: "Floor plan marked on the floor with duct tape to guide all subsequent works.",
    status: "in-progress",
    startDay: 7,
    durationDays: 2,
    checkpoint: false,
  },
  {
    id: "6.4",
    number: "6.4",
    name: "Electrical & Wiring",
    detail: "Electrical and wiring work. Runs in parallel with other applicable stages.",
    status: "in-progress",
    startDay: 8,
    durationDays: 14,
    checkpoint: false,
  },
  {
    id: "6.5",
    number: "6.5",
    name: "Walls, Doors & Windows",
    detail: "Wall works, door and window installation. May run in parallel with ceiling work.",
    status: "upcoming",
    startDay: 10,
    durationDays: 16,
    checkpoint: false,
  },
  {
    id: "6.6",
    number: "6.6",
    name: "Ceiling Works",
    detail: "Ceiling construction and finishing. Can run in parallel with 6.5.",
    status: "upcoming",
    startDay: 12,
    durationDays: 12,
    checkpoint: false,
  },
  {
    id: "6.7",
    number: "6.7",
    name: "Deep Clean #1",
    detail: "Mandatory checkpoint after masonry or high-dust work, before flooring begins.",
    status: "upcoming",
    startDay: 26,
    durationDays: 2,
    checkpoint: true,
  },
  {
    id: "6.8",
    number: "6.8",
    name: "Flooring",
    detail: "Flooring installation after the first deep clean.",
    status: "blocked",
    startDay: 28,
    durationDays: 10,
    checkpoint: false,
    blockedBy: "6.7",
  },
  {
    id: "6.9",
    number: "6.9",
    name: "Interior Elements & Installation",
    detail: "Decor, custom pieces, furniture delivery, and light fittings. Supplier items on site.",
    status: "upcoming",
    startDay: 36,
    durationDays: 8,
    checkpoint: false,
  },
  {
    id: "6.10",
    number: "6.10",
    name: "Deep Clean #2",
    detail: "Mandatory second deep clean after installation, before final stages.",
    status: "upcoming",
    startDay: 44,
    durationDays: 2,
    checkpoint: true,
  },
  {
    id: "6.11",
    number: "6.11",
    name: "Soft Clean",
    detail: "Final soft clean after all furniture and fittings are in place.",
    status: "blocked",
    startDay: 46,
    durationDays: 2,
    checkpoint: false,
    blockedBy: "6.10",
  },
  {
    id: "6.12",
    number: "6.12",
    name: "Audit & Snagging",
    detail: "Full walkthrough. Review detailing against design drawings. Flag and resolve issues.",
    status: "upcoming",
    startDay: 48,
    durationDays: 3,
    checkpoint: false,
  },
  {
    id: "6.13",
    number: "6.13",
    name: "Handover",
    detail: "Formal handover to the client.",
    status: "upcoming",
    startDay: 51,
    durationDays: 1,
    checkpoint: false,
  },
];

export const SITE_TOTAL_DAYS = 52;
