import type { DetailCategory, DirectorProject } from "@/types/detail";

export const DETAIL_CATEGORIES: DetailCategory[] = [
  {
    id: "electrical",
    label: "Electrical",
    icon: "bolt",
    color: "#F59E0B",
    accentBg: "#FEF3C7",
    estimate: 2_850_000,
    complete: true,
    notes: "All wiring schematics reviewed and approved by MEP consultant.",
    files: [
      { id: 1, name: "Electrical_Layout_v2.pdf", type: "pdf", size: "4.1 MB", date: "21 Jul 2026" },
      { id: 2, name: "Wiring_Schematic.dwg", type: "dwg", size: "2.7 MB", date: "22 Jul 2026" },
      { id: 3, name: "Panel_Schedule_Final.pdf", type: "pdf", size: "1.2 MB", date: "23 Jul 2026" },
    ],
  },
  {
    id: "flooring",
    label: "Flooring",
    icon: "layers",
    color: "#8B5CF6",
    accentBg: "#EDE9FE",
    estimate: 4_200_000,
    complete: false,
    notes: "",
    files: [
      { id: 4, name: "Flooring_Layout_v1.pdf", type: "pdf", size: "3.5 MB", date: "24 Jul 2026" },
      { id: 5, name: "Tile_Pattern_Lobby.dwg", type: "dwg", size: "1.9 MB", date: "24 Jul 2026" },
    ],
  },
  {
    id: "ceiling",
    label: "Ceiling",
    icon: "roofing",
    color: "#0E7C86",
    accentBg: "rgba(14,124,134,0.10)",
    estimate: 3_100_000,
    complete: false,
    notes: "",
    files: [{ id: 6, name: "Ceiling_Plan_Lobby.pdf", type: "pdf", size: "2.8 MB", date: "25 Jul 2026" }],
  },
  {
    id: "walls",
    label: "Walls, Doors & Windows",
    icon: "door_front",
    color: "#0891B2",
    accentBg: "#E0F7FA",
    estimate: 5_600_000,
    complete: false,
    notes: "",
    files: [],
  },
  {
    id: "furniture",
    label: "Furniture",
    icon: "chair",
    color: "#059669",
    accentBg: "#D1FAE5",
    estimate: 7_200_000,
    complete: false,
    notes: "",
    files: [{ id: 7, name: "FF&E_Schedule_v1.pdf", type: "pdf", size: "5.6 MB", date: "26 Jul 2026" }],
  },
  {
    id: "interior",
    label: "Interior Elements",
    icon: "palette",
    color: "#EC4899",
    accentBg: "#FCE7F3",
    estimate: 1_900_000,
    complete: false,
    notes: "",
    files: [
      { id: 8, name: "Decorative_Elements.pdf", type: "pdf", size: "2.1 MB", date: "26 Jul 2026" },
      { id: 9, name: "Custom_Artwork_Spec.pdf", type: "pdf", size: "0.9 MB", date: "27 Jul 2026" },
    ],
  },
];

export const DIRECTOR_PROJECTS: DirectorProject[] = [
  {
    id: 1,
    name: "Marchetti Villa",
    client: "Giulia Marchetti",
    designer: { initials: "PN", color: "#7C3AED", name: "Priya Nair" },
    daysInPhase: 8,
    status: "awaiting",
    categories: {
      electrical: true,
      flooring: false,
      ceiling: false,
      walls: false,
      furniture: true,
      interior: false,
    },
  },
  {
    id: 2,
    name: "Bianchi Office Fit-Out",
    client: "Federico Bianchi",
    designer: { initials: "AP", color: "#0891B2", name: "Ashan Perera" },
    daysInPhase: 14,
    status: "awaiting",
    categories: {
      electrical: true,
      flooring: true,
      ceiling: true,
      walls: false,
      furniture: false,
      interior: false,
    },
  },
  {
    id: 3,
    name: "Romano Penthouse",
    client: "Luca Romano",
    designer: { initials: "DS", color: "#D97706", name: "Dilani Silva" },
    daysInPhase: 5,
    status: "awaiting",
    categories: {
      electrical: false,
      flooring: false,
      ceiling: false,
      walls: false,
      furniture: false,
      interior: false,
    },
  },
  {
    id: 4,
    name: "Visconti Showroom",
    client: "Alessandra Visconti",
    designer: { initials: "RF", color: "#059669", name: "Roshan Fernando" },
    daysInPhase: 21,
    status: "complete",
    categories: {
      electrical: true,
      flooring: true,
      ceiling: true,
      walls: true,
      furniture: true,
      interior: true,
    },
  },
  {
    id: 5,
    name: "De Luca Townhouse",
    client: "Marco De Luca",
    designer: { initials: "CG", color: "#6366F1", name: "Chamari Gunasena" },
    daysInPhase: 3,
    status: "awaiting",
    categories: {
      electrical: true,
      flooring: false,
      ceiling: false,
      walls: false,
      furniture: false,
      interior: false,
    },
  },
];
