export type ClientStatus = 'Active' | 'Lead' | 'Past'
export type LeadSource = 'Referral' | 'Instagram' | 'Website' | 'Walk-in'
export type LeadStage = 'new' | 'meeting' | 'proposal' | 'won' | 'lost'

export interface Client {
  id: number
  initials: string
  color: string
  name: string
  company: string
  phone: string
  email: string
  address: string
  preferredContact: 'Email' | 'Phone' | 'WhatsApp'
  status: ClientStatus
  source: LeadSource
  stage?: LeadStage
  linkedProjects: number
  activeProjects: number
  totalInvoiced: string
  lastContact: string
  followUpDate?: string
  assignedTo: string
  assignedInitials: string
  notes?: string
}

export const CLIENTS: Client[] = [
  {
    id: 1,
    initials: 'GM',
    color: '#1B2A4A',
    name: 'Giulia Marchetti',
    company: 'Marchetti Holdings',
    phone: '+39 02 1234 5678',
    email: 'giulia@marchetti.it',
    address: 'Via della Spiga 14, Milan',
    preferredContact: 'Email',
    status: 'Active',
    source: 'Referral',
    linkedProjects: 3,
    activeProjects: 2,
    totalInvoiced: '€ 148,000',
    lastContact: 'Jul 28, 2025',
    assignedTo: 'Sofia Marchetti',
    assignedInitials: 'SM',
  },
  {
    id: 2,
    initials: 'FB',
    color: '#0E7C86',
    name: 'Federico Bianchi',
    company: 'Bianchi Group',
    phone: '+39 02 9876 5432',
    email: 'f.bianchi@bianchigroup.com',
    address: 'Piazza San Babila 3, Milan',
    preferredContact: 'Phone',
    status: 'Active',
    source: 'Referral',
    linkedProjects: 2,
    activeProjects: 1,
    totalInvoiced: '€ 92,500',
    lastContact: 'Jul 25, 2025',
    assignedTo: 'Chiara Romano',
    assignedInitials: 'CR',
  },
  {
    id: 3,
    initials: 'LR',
    color: '#3FA66B',
    name: 'Luca Romano',
    company: 'Romano Gallery',
    phone: '+39 06 5555 1234',
    email: 'luca@romanogallery.com',
    address: 'Via Margutta 51, Rome',
    preferredContact: 'Email',
    status: 'Active',
    source: 'Instagram',
    linkedProjects: 1,
    activeProjects: 1,
    totalInvoiced: '€ 55,000',
    lastContact: 'Jul 20, 2025',
    assignedTo: 'Lorenzo Pieri',
    assignedInitials: 'LP',
  },
  {
    id: 4,
    initials: 'AV',
    color: '#243458',
    name: 'Alessandra Visconti',
    company: 'Visconti Real Estate',
    phone: '+39 02 7777 8888',
    email: 'avisconti@viscontigroup.it',
    address: 'Corso Venezia 22, Milan',
    preferredContact: 'WhatsApp',
    status: 'Active',
    source: 'Referral',
    linkedProjects: 4,
    activeProjects: 1,
    totalInvoiced: '€ 212,000',
    lastContact: 'Jul 30, 2025',
    assignedTo: 'Sofia Marchetti',
    assignedInitials: 'SM',
  },
  {
    id: 5,
    initials: 'MD',
    color: '#F5A623',
    name: 'Marco De Luca',
    company: 'De Luca Studios',
    phone: '+39 055 3333 2222',
    email: 'm.deluca@delucadesign.com',
    address: 'Lungarno Corsini 8, Florence',
    preferredContact: 'Email',
    status: 'Lead',
    source: 'Instagram',
    stage: 'meeting',
    linkedProjects: 0,
    activeProjects: 0,
    totalInvoiced: '€ 0',
    lastContact: 'Jul 18, 2025',
    followUpDate: 'Aug 3, 2025',
    assignedTo: 'Chiara Romano',
    assignedInitials: 'CR',
  },
  {
    id: 6,
    initials: 'RF',
    color: '#0E7C86',
    name: 'Renata Ferretti',
    company: 'Ferretti Villa Group',
    phone: '+39 02 4444 5555',
    email: 'renata@ferrettivilla.it',
    address: 'Via Montenapoleone 9, Milan',
    preferredContact: 'Phone',
    status: 'Active',
    source: 'Referral',
    linkedProjects: 2,
    activeProjects: 1,
    totalInvoiced: '€ 78,500',
    lastContact: 'Jul 22, 2025',
    assignedTo: 'Lorenzo Pieri',
    assignedInitials: 'LP',
  },
  {
    id: 7,
    initials: 'PN',
    color: '#6B7280',
    name: 'Pietro Negroni',
    company: 'Negroni Hospitality',
    phone: '+39 02 1111 2222',
    email: 'p.negroni@negronihotels.com',
    address: 'Via Torino 45, Milan',
    preferredContact: 'Email',
    status: 'Lead',
    source: 'Website',
    stage: 'proposal',
    linkedProjects: 0,
    activeProjects: 0,
    totalInvoiced: '€ 0',
    lastContact: 'Jul 15, 2025',
    followUpDate: 'Jul 29, 2025',
    assignedTo: 'Sofia Marchetti',
    assignedInitials: 'SM',
    notes: 'Hotel lobby redesign — 3 properties',
  },
  {
    id: 8,
    initials: 'CC',
    color: '#9CA3AF',
    name: 'Carla Conti',
    company: 'Conti Properties',
    phone: '+39 06 9999 0000',
    email: 'cconti@contiproperties.it',
    address: 'Parioli, Rome',
    preferredContact: 'WhatsApp',
    status: 'Past',
    source: 'Walk-in',
    linkedProjects: 2,
    activeProjects: 0,
    totalInvoiced: '€ 44,000',
    lastContact: 'Mar 10, 2025',
    assignedTo: 'Chiara Romano',
    assignedInitials: 'CR',
  },
  {
    id: 9,
    initials: 'EG',
    color: '#1B2A4A',
    name: 'Elena Grassi',
    company: 'Grassi Interiors',
    phone: '+39 02 6666 7777',
    email: 'elena@grassiint.com',
    address: 'Brera, Milan',
    preferredContact: 'Email',
    status: 'Lead',
    source: 'Instagram',
    stage: 'new',
    linkedProjects: 0,
    activeProjects: 0,
    totalInvoiced: '€ 0',
    lastContact: 'Jul 29, 2025',
    followUpDate: 'Aug 5, 2025',
    assignedTo: 'Lorenzo Pieri',
    assignedInitials: 'LP',
    notes: 'Residential — 4-bedroom apartment redesign',
  },
  {
    id: 10,
    initials: 'SR',
    color: '#3FA66B',
    name: 'Sergio Ricci',
    company: 'Ricci Architecture',
    phone: '+39 02 3333 4444',
    email: 's.ricci@ricciarch.it',
    address: 'Navigli, Milan',
    preferredContact: 'Phone',
    status: 'Lead',
    source: 'Referral',
    stage: 'new',
    linkedProjects: 0,
    activeProjects: 0,
    totalInvoiced: '€ 0',
    lastContact: 'Jul 27, 2025',
    followUpDate: 'Aug 7, 2025',
    assignedTo: 'Chiara Romano',
    assignedInitials: 'CR',
    notes: 'Office fit-out — co-working space',
  },
]

export const COMM_LOG = [
  {
    id: 1,
    type: 'meeting' as const,
    date: 'Jul 28, 2025',
    time: '10:30 AM',
    member: 'Sofia Marchetti',
    initials: 'SM',
    note: 'Reviewed Phase 2 moodboard selections. Client approved travertine tile option and requested two additional fabric swatches for the master bedroom. Next meeting scheduled for Aug 12.',
  },
  {
    id: 2,
    type: 'email' as const,
    date: 'Jul 22, 2025',
    time: '3:15 PM',
    member: 'Chiara Romano',
    initials: 'CR',
    note: 'Sent revised lighting plan and preliminary cost estimate for the living area. Client acknowledged receipt and will revert by end of week.',
  },
  {
    id: 3,
    type: 'call' as const,
    date: 'Jul 15, 2025',
    time: '11:00 AM',
    member: 'Sofia Marchetti',
    initials: 'SM',
    note: 'Call to confirm procurement schedule. Client is available for site visit on July 31. Discussed timeline for kitchen cabinet installation.',
  },
  {
    id: 4,
    type: 'meeting' as const,
    date: 'Jul 5, 2025',
    time: '2:00 PM',
    member: 'Lorenzo Pieri',
    initials: 'LP',
    note: 'Concept presentation at client office. Presented 3 design directions — client selected Direction B (Contemporary Minimal). Requested minor adjustments to palette.',
  },
  {
    id: 5,
    type: 'email' as const,
    date: 'Jun 28, 2025',
    time: '9:45 AM',
    member: 'Chiara Romano',
    initials: 'CR',
    note: 'Sent project brief and engagement letter for signature. Attached fee structure and phased timeline overview.',
  },
]

export const PIPELINE_CARDS = {
  new: [
    { id: 101, client: 'Elena Grassi',   company: 'Grassi Interiors',    source: 'Instagram', followUp: 'Aug 5',  initials: 'LP', overdue: false },
    { id: 102, client: 'Sergio Ricci',   company: 'Ricci Architecture',  source: 'Referral',  followUp: 'Aug 7',  initials: 'CR', overdue: false },
    { id: 103, client: 'Paola Ferrara',  company: 'Ferrara Group',       source: 'Website',   followUp: 'Aug 2',  initials: 'SM', overdue: false },
  ],
  meeting: [
    { id: 201, client: 'Marco De Luca',  company: 'De Luca Studios',     source: 'Instagram', followUp: 'Aug 3',  initials: 'CR', overdue: false },
    { id: 202, client: 'Nina Colombo',   company: 'Colombo Properties',  source: 'Walk-in',   followUp: 'Jul 30', initials: 'SM', overdue: true  },
  ],
  proposal: [
    { id: 301, client: 'Pietro Negroni', company: 'Negroni Hospitality', source: 'Website',   followUp: 'Jul 29', initials: 'SM', overdue: true  },
    { id: 302, client: 'Sara Galli',     company: 'Galli Family Office', source: 'Referral',  followUp: 'Aug 8',  initials: 'LP', overdue: false },
  ],
  won: [
    { id: 401, client: 'Giulia Marchetti', company: 'Marchetti Holdings', source: 'Referral',  followUp: '',    initials: 'SM', overdue: false },
    { id: 402, client: 'Renata Ferretti',  company: 'Ferretti Villa',     source: 'Referral',  followUp: '',    initials: 'LP', overdue: false },
  ],
  lost: [
    { id: 501, client: 'Carla Conti',    company: 'Conti Properties',    source: 'Walk-in',   followUp: '',    initials: 'CR', overdue: false },
  ],
}
